# Generated by Django 5.0.3 on 2024-04-03 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "borrowings",
            "0005_remove_borrowing_book_id_remove_borrowing_user_id_and_more",
        ),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="borrowing_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="borrowings.borrowing",
            ),
            preserve_default=False,
        ),
    ]
