# Generated by Django 5.0.3 on 2024-04-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_alter_borrowing_actual_return_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="book_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="user_id",
            field=models.PositiveIntegerField(),
        ),
    ]
