# Generated by Django 5.0.3 on 2024-04-02 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books_service", "0002_alter_book_daily_fee"),
        ("borrowings", "0004_alter_borrowing_borrow_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="book_id",
        ),
        migrations.RemoveField(
            model_name="borrowing",
            name="user_id",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to="books_service.book",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="borrowing",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
